### ISSUE TITLE
Unable to install in Symfony Flex project

### ISSUE THREAD

**Issue by PabloKowalczyk** [Matthimatiker/OpcacheBundle#16]
Symfony Flex (http://fabien.potencier.org/symfony4-demo.html) project doesn't have `symfony/symfony` as  dependency and this bundle requires `symfony/symfony`.

**Comment by MatthiasMolitor** [comment]
Hi @PabloKowalczyk,

thanks for pointing that out! Please check if version 0.5.0 works for you.

**Comment by PabloKowalczyk** [comment]
Thanks @Matthimatiker.
It is now installable (good job) but profiler throws exceptions:
```
The profiler template "MatthimatikerOpcacheBundle:DataCollector:ByteCodeCache.html.twig" for data collector "matthimatiker_opcache.byte_code_cache" does not exist.
```
After installing `symfony/templating` and `symfony/asset` packages and adding configuration:
```yml
framework:
    templating:
      engine: "twig"
```
everything works great.

I think you should consider adding these packages as dependencies and add some information about configuration. Alternatively you can stop using this notation (`MatthimatikerOpcacheBundle:DataCollector:ByteCodeCache.html.twig`) and do not depend on symfony's twig file loader.

Thanks anyway :)

**Comment by MatthiasMolitor** [comment]
@PabloKowalczyk I am glad to hear that the bundle is at least usable for you now :-)

Thanks for sharing the details about the further problems that arised, that is really helpful! I might have a look into that within the next weeks.
I did not yet find the time to tinker around with Symfony Flex in depth.
